### ISSUE TITLE
Some elements not dealed with properly on Nightly 43.0a1

### ISSUE THREAD

**Issue by lychichem** [johngraciliano/simplewhite#1]
1. Under private mode, the logo circled is not shown.
   ![default](https://cloud.githubusercontent.com/assets/9316590/9934471/4185cb86-5d84-11e5-969d-df11e4da15d5.PNG)
2. In web console, show rulers icon is not shown.
   ![1](https://cloud.githubusercontent.com/assets/9316590/9934566/ceb23fc6-5d84-11e5-8d9a-5ded31aaaeae.PNG)
3. I don't know why you add a toggle button here, but please keep it same as default theme.
   ![2](https://cloud.githubusercontent.com/assets/9316590/9934575/d5b29780-5d84-11e5-9d7a-5f5e4a775dea.PNG)
4. The blocked elements icon in URL bar is not shown. It relates to new UX introduced to Nightly just in a few weeks.
   ![3](https://cloud.githubusercontent.com/assets/9316590/9934578/dd011386-5d84-11e5-945e-4e82ba7a0b87.PNG)

**Comment by lychichem** [comment]
In brief, I don't suggest Nightly users to use this theme right now. And we need to fix these problems before we declare that this theme can work on Nightly 43.0a1

**Comment by johngraciliano** [comment]
Thank you for your feedback.
I will work on solving those issues soon.  I however see no reason why to keep the minimize button in # 3 hidden.  If it works, why hide it? (I am aware that it does change when minimized as it should.)
I presume you tested on windows 10.  I hope there were no issues regarding O.S. compatibility.  Please let me know if there are problems affecting earlier versions of Firefox.  Certainly some of those issues may affect some earlier versions.
I will not be surprised if more compatibility problems arise with Nightly since it keeps moving ahead.  I know some of those can propagate to Aurora, as I have seen happen.  I hope there are no issues related to the current release candidate of which I am unaware.

**Comment by lychichem** [comment]
If you say OS compatibility, it's just okay on windows. But maybe you should find a user who uses linux to test it. Why I ask you to keep it as the default theme is to make sure this function will not cause issues in the future, if you think it will not, it's just okay. But maybe you should test under high DPI mode(i.e. 200%) because some users reported that themes will behave differently under this situation. I know test for nightly is hard, and therefor I don't use theme on nightly.

**Comment by johngraciliano** [comment]
I am just realizing you have high standards.  Currently, Simple White has bad support for the inspector and other parts of the developer tools in the latest official release of Firefox 40.  This includes the the problem of not showing the rulers icon!  I think the icon for the Shader Editor tool disappears in Firefox 41.  The problem with the private mode page extends to Aurora and it includes missing the green check marks and yellow warning signs.  The missing blocked elements icon affects Aurora too.  All this could take me a couple of days...  I hope there is nothing else that affects the current Firefox nor the one being released in the coming days.  I am aware of a probably more pressing issue concerning support for the Firefox in the Mac and I am not expecting to have it solved before I can send something to A.M.O.

**Comment by lychichem** [comment]
Fixed by comment 8738cd8
