### ISSUE TITLE
Double System Button Icons

### ISSUE THREAD

**Issue by Matix8** [johngraciliano/simplewhite#11]
![windows icons](https://cloud.githubusercontent.com/assets/4058409/10864010/d9773626-8022-11e5-9272-441b57847e5b.png)

I just installed the theme on FF 41.0.2 (Windows 10 Pro) and noticed that the Minimize, Maximize, and Close buttons have double icons.

**Comment by johngraciliano** [comment]
Thank you for the report.  We need to know if this problem is present in both versions [2.2.b18.x1.03](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x1.03) and [2.2b18.x1.02](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x1.02) or if only in one of them.  We may also need to know if there are changes to the Windows default theme.

**Comment by Matix8** [comment]
2.2.b18.x1.03  -  Problem Exists
2.2b18.x1.02   -  No Problem

**Comment by johngraciliano** [comment]
@Matix8:  Please verify release [v2.2b18.x1.03+](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x1.03%2B) solves this issue.  I will close it in a day or two if there is no reply.

**Comment by Matix8** [comment]
@johngraciliano: the issue appears to be resolved with v2.2b18.x1.03+.  Thank you.

**Comment by johngraciliano** [comment]
I published a new version v2.2b18.x1.04 that has some code related to the issue.  I hope it re-enables showing colored title bars because it contains part of the code that @lychichem contributed.  I do not think it brings any problem, yet I am not sure how it may affect the earlier versions of Firefox.  If I nobody reports this issue reappears in it, I will close this again and send the version to AMO.

**Comment by johngraciliano** [comment]
I am closing this because nobody has replied the problem has resurfaced.
