### ISSUE TITLE
Colored title bar not colored

### ISSUE THREAD

**Issue by ghost** [johngraciliano/simplewhite#21]
In [this previous issue comment](https://github.com/johngraciliano/simplewhite/issues/11#issuecomment-158817919) it's hinted, that Simple White should respect the colored title bars, yet on my Windows 10 laptop this doesn't happen, the entire windows remains white - see the screenshot.

Colored title bars are shown on the [Mozilla addon page as well](https://addons.cdn.mozilla.net/user-media/previews/full/167/167184.png?modified=1445835658).

Am I doing something wrong, is this feature not available anymore?

![screenshot](https://cloud.githubusercontent.com/assets/6289234/12498526/9dba8680-c0a3-11e5-8d21-849a2f151d55.png)

**Comment by Lootyhoof** [comment]
The use of coloured titlebars appears to have been reverted in f117d3212acf174df53a5c08efc63eac23aa9cb9, due to #11. In any case, I personally wouldn't recommend attempting to add this into the theme itself (at least, if you intend to distribute it) because there is no way of detecting whether the window frame is dark in Windows 10 like there is in Windows 8 ([bug 1196266](https://bugzilla.mozilla.org/show_bug.cgi?id=1196266) is tracking this), so it's possible things could look bad if someone has a dark window frame. If you want to make this work on your local device, there exists a userstyle (i.e. userChrome.css/Stylish style) by [Lars-Erik Østerud](http://firefox.osterud.name) that can do this.

As for your comment about the AMO screenshot, @johngraciliano appears to be on Windows 8, which natively does have coloured titlebars.

**Comment by ghost** [comment]
Thanks for the detailed explanation and advice, @Lootyhoof! I tried Lars-Erik's userstyle but it didn't look ideal with my current Windows 10 color accent (inactive tabs too light with white text - see the screenshot), so now I totally understand the concerns you've mentioned. Cheers!

![screenshot](https://cloud.githubusercontent.com/assets/6289234/12524497/a8846300-c15d-11e5-8c71-5b6689209bd7.PNG)

**Comment by Lootyhoof** [comment]
To be honest, that userstyle accounts for the default Australis theme only - you can safely remove this line in it:
`tab:not([selected="true"]) .tab-text{color:#FFFFFF!important}`
This will fix your issue.

**Comment by ghost** [comment]
PERFECT! Now the theme looks exactly the way I wanted! Thanks a lot!

**Comment by johngraciliano** [comment]
Yes it is true I use **Windows 8**, yet for the last few hours its been trying to finish an upgrade to **Windows 8.1** I do not remember agreeing to have.  It seems like an unavoidable annoyance.  It makes me ponder why I have not moved to **Linux**.  
p.s. Thank you @Lootyhoof for taking care of this issue.  I really have no idea how things look in **Windows 10**, except for those images...  
p.p.s. I certainly do not want to be forced to upgrade to **Windows 10**.

**Comment by johngraciliano** [comment]
@hluposti:
Did you ever tried adding a background using the extension [Persona Switcher](https://addons.mozilla.org/en-US/firefox/addon/personaswitcher/)?  Currently, you should be able to switch your toolbox area to something like:
![now](https://cloud.githubusercontent.com/assets/13938911/12538606/b401c9da-c2ab-11e5-9e1c-0aa9764e0577.png)
After the next release this should become like:
![next](https://cloud.githubusercontent.com/assets/13938911/12538610/d0c4a646-c2ab-11e5-8a02-f4314bc118ed.png)
The samples are using the light theme (persona) [нежный зеленый](https://addons.mozilla.org/en-US/firefox/addon/%D0%BD%D0%B5%D0%B6%D0%BD%D1%8B%D0%B9-%D0%B7%D0%B5%D0%BB%D0%B5%D0%BD%D1%8B%D0%B9/).  Yet, they are using **Windows 8**, I have no idea if using personas has any desirable effect in **Windows 10**.  You may find or create a persona with a flat background with your desired color or try [HoriBlack (transparent)](https://addons.mozilla.org/en-US/firefox/addon/horiblack-transparent/), which should show your default window background!  Again, I have no idea what effect that has in **Windows 10**.  If you try it please comment on what you find.

**Comment by ghost** [comment]
The green one looks like this under Windows 10:
![russian](https://cloud.githubusercontent.com/assets/6289234/12538799/91ba8492-c2e3-11e5-8910-edf4afa24f7f.PNG)
...similar to what you posted, though the window buttons are transparent.

HoriBlack, however, doesn't work as transparent:
![hori](https://cloud.githubusercontent.com/assets/6289234/12538804/b7764cb6-c2e3-11e5-96ad-cea841712836.PNG)

**Comment by johngraciliano** [comment]
@hluposti:
Thank you for the comment with images.  You bring to my attention the fact all personas, with dark or bright text, use the same images for the _max:min:close_ buttons in **Windows 10**.  That is inherited from the default theme.  These buttons will be different in the upcoming release, i.e., black buttons will be used when the persona uses dark text.  The white buttons for personas with bright text will be different too.  **Mozilla** should change them in the default theme too!
![buttons](https://cloud.githubusercontent.com/assets/13938911/12550050/456625b4-c32f-11e5-80e1-476dbd885a17.png)
I hope you like how light themes work in the next release.  Unfortunately there is nothing I can do let the native toolbar color be seen in **Windows 10** at this moment.

p.s. With personas, the close button will toggle white/black when hovered.  Please let me know if this behavior is not standard.

**Comment by Lootyhoof** [comment]
The close button should never be black when hovered; it is always white in Windows 10 on hover. Great work otherwise, though the outline should potentially be clearer, as there can be visibility issues on particularly busy personas:

![Visibility issues](http://i.imgur.com/059ylxH.png)

**Comment by johngraciliano** [comment]
@Lootyhoof:  If you are stating the close button that shows when personas with bright text are used (on **Windows 10**) should remain white when hovered then that shall be the behavior after the next release.   If I misunderstood, please correct me.
I computed the effect of the border on the buttons to be about the same of that used in the top border of the _navigation bar_.  This may change with the screen resolution, but I do not think it becomes less than 75% of that other one.\*  I preferred to have no border.  But I left this to as a guide to force contrast so the black button is visible even on a black background and the white button on a white background.  Yet I do not want buttons with a visible outline.  I do not want to change this for two reasons:  The first is that the buttons are already thicker than the standard buttons (these are based on buttons used with high contrast themes, yet those have no border).  The second is that this issue is more a responsibility of the persona (light theme) designer or the person that chooses it, that is, as I change this theme to accommodate for various personas I am changing the theme's character.  Those buttons are already more visible when compared to how standard theme buttons look when place on the tabs bar. There is always a trade in visual elements between usefulness and aesthetic preferences.  Where to draw the line is always a personal choice.
![sample2](https://cloud.githubusercontent.com/assets/13938911/12637187/3db1a756-c561-11e5-9237-533619a375dd.png)

p.s. I know it is my fault, but all this discussion should have taken place in a different thread (issue).

---

*I do not want it any stronger than the border on top of the _navigation bar_.

**Comment by bwat47** [comment]
This is the best userstyle I've found for a colored titlebar on windows 10 with simple white. It seems to work properly with both light and dark background colors (with light bg min/max close buttons are dark, with dark bg they are white), and doesn't have any issues with the alignment of min/max/close buttons on hover:

http://pastebin.com/pgSp1vYZ

![6esrozk](https://cloud.githubusercontent.com/assets/1442520/14129373/916a624a-f5f7-11e5-9c8e-4b01a11fa980.png)

**Comment by bwat47** [comment]
I don't know much css, but I managed to throw together an improved version of the above that should be (as far as I can tell) 100% compatible with both light and dark titlebar colors and doesn't have any glitches/alignment issues as far as I can tell :). 

I uploaded it to userstyles.org here: https://userstyles.org/styles/126206/simple-white-theme-windows-10-colored-titlebar

There's 2 variants, use the light one if you have a light colored titlebar, use the dark one if you have a dark colored titlebar.

The style is mostly compatible with both without changes, the only change between those two variants is the tab overflow/tab menu icons (they are white in the dark titlebar variant, black in the light titlebar variant).

EDIT 4/2/16: updated the dark titlebar userstyle so that when the window is inactive the tab overflow icons turn black like the min/max/close buttons do

EDIT: 11/16/16: At some point my hacky method for the white tab overflow icons got a little broken (the tab overflow icon on the right started pointing the wrong direction) so added more hackiness to re-orient that icon

![dark](https://cloud.githubusercontent.com/assets/1442520/14195414/080bf504-f787-11e5-8ea8-75965e189ed2.png)

![light](https://cloud.githubusercontent.com/assets/1442520/14195420/10bdebda-f787-11e5-8748-cd82fa735e07.png)

**Comment by johngraciliano** [comment]
Thank you so much for your contribution.  I noted it within the _Developer's Comments_ of the theme page at A.M.O.
