### ISSUE TITLE
ff 53?

### ISSUE THREAD

**Issue by Mioni** [johngraciliano/simplewhite#35]
How I do to use it? He says it's not compatible

**Comment by johngraciliano** [comment]
I apologize, I have not updated yet the AMO because I do not have an official release yet.  There are a few changes in **Firefox Nightly 53.0a1** that I had neglected and I am just testing (error pages and container tabs).  There had been a few changes to the ***Developer Tools*** (I am changing the dark theme (#34) but it needs testing from volunteers).  I am also trying to address bug #30 but I need someone to test ***my*** solution.  I believe I posted a release [here](https://github.com/johngraciliano/simplewhite/releases) that may work (partially) with **Firefox Nightly 53.0a1**. 
Again, I am sorry for the delay.  I can certainly post an updated version soon but I do not want to post it on AMO until it is tested for #34 and perhaps also #30.

PS. Happy New Year.

**Comment by johngraciliano** [comment]
Sorry, I am still working with changes for **Firefox 53** because of changes in the ***Developer Tools***.  Even though it may be easy to leave the default tools, I take special care for details in them, e.g., for the ***Firebug Theme***.  But this presents spacial complications in the rapid changes in the tools towards an html presentation (non XML).  I seem not to be able to catch up with everything.

**Comment by johngraciliano** [comment]
@Mioni:
Please try installing [v2.2b18.x2.0+S4](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.0%2BS4)  by clinking [here](https://github.com/johngraciliano/simplewhite/releases/download/v2.2b18.x2.0%2BS4/SimpleWhiteX.S4.xpi)

**Comment by Mioni** [comment]
Very good thank you for this beautiful theme.
