### ISSUE TITLE
Tabs in the about:newtab page don't slide when you click the X button to close it.

### ISSUE THREAD

**Issue by maicol07** [johngraciliano/simplewhite#36]
Hi,
tabs in the about:newtab page don't slide when one is closing. For example, if I close the first tab on the left, (see image below) the next tabs don't slide until I have the cursor on the closed tab's shape. Why?
Thanks
![165366](https://cloud.githubusercontent.com/assets/9463142/22023729/a4bf915a-dcc7-11e6-8991-cfafd90cdd8c.png)
Edit: I tried to download the latest pre-release from [this post](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.0%2BS4) and it works. Thanks. Only one request now: can you revision the plugin for colored title bar in Windows 10? If I use a third-party theme, the control buttons (close, maximize/minimize and reduce)  change into Windows default. Thanks again.

**Comment by johngraciliano** [comment]
Hi,
Yes, I updated about:newtab in the last version I loaded here and I hope it works better.  I may change it even more and perhaps remove the perspective view from it to allow a better animation when tabs are removed.  I understand little about the colored title bar issue because I do not have Windows 10.  I simply try to follow the changes in the default provided by Mozilla regarding that (to some extent).  You may open another issue regarding that and explain a bit better for me.

P.S. Please note pinned tabs do not move from their position when you remove other tabs!

P.P.S.  Does the last Experimental release solve #30? That is: Can tabs be selected when the cursor scrolls at the top of the screen while the Firefox is maximized? (Yes or No)

**Comment by maicol07** [comment]
If I tried well, it works (for issue #30 ). Thanks for your great work!!

**Comment by johngraciliano** [comment]
@maicol07:
Thank you for testing #30.  It makes me happy that I have a solution in the experimental release.  I hope I can have a standard release early next week.
Regarding _"...title bar in Windows 10? If I use a third-party theme, the control buttons (close, maximize/minimize and reduce) change into Windows default."_  The minimize, maximize, close buttons use images from **Firefox**'s theme in **Windows 10**.  The images are made to match the images in **Windows 10** O.S.  That is done in the **Firefox**'s ***default*** theme and I copied it (I may had changed the images slightly).  If you use a third party theme for **Windows** that has different images for those buttons, those images would have to be copied into the theme in order to be matched.  

P.S. I have no idea if the original button images from the O.S. are behind those drawn by **Firefox**.

**Comment by maicol07** [comment]
The default Windows 10 Firefox title bar buttons matches perfectly with the originals. Maybe you can use the images of the current theme applied...

**Comment by johngraciliano** [comment]
If the ***default*** theme has a way of reading the images I try to copy whatever is done there but I know of no way to access the images used by the O.S.

**Comment by maicol07** [comment]
If it can help you, I can give you a theme located in C:/Windows/Resources/Themes/

**Comment by johngraciliano** [comment]
If you want custom images you would have to add your own code.  The current lines are:
````
        #titlebar-min {
          list-style-image: url(chrome://browser/skin/caption-buttons.svg#minimize);
        }
        #titlebar-max {
          list-style-image: url(chrome://browser/skin/caption-buttons.svg#maximize);
        }
        #main-window[sizemode="maximized"] #titlebar-max {
          list-style-image: url(chrome://browser/skin/caption-buttons.svg#restore);
        }
        #titlebar-close {
          list-style-image: url(chrome://browser/skin/caption-buttons.svg#close);
        }
        #titlebar-close:hover {
          list-style-image: url(chrome://browser/skin/caption-buttons.svg#close-white);
        }
```` 
So your code would look like:
````
        #titlebar-min {
          list-style-image: url(file:///C:/Minimize-Image-Location) !important;
        }
        #titlebar-max {
          list-style-image: url(file:///C:/Maximize-Image-Location) !important;
        }
        #main-window[sizemode="maximized"] #titlebar-max {
          list-style-image: url(file:///C:/Restore-Image-Location) !important;
        }
        #titlebar-close {
          list-style-image: url(file:///C:/Close-Image-Location) !important;
        }
        #titlebar-close:hover {
          list-style-image: url(file:///C:/Close-Hover-Image-Location) !important;
        }
````
I have never tried it, but I suppose it would work.  I believe the images should be 12 pixels by 12 pixels, but perhaps other sizes could work.  You could add the code with ***Stylish*** or via ```userChrome.css```

**Comment by maicol07** [comment]
Thanks for the code, but there is a problem: Windows themes haven't images for buttons. They are in a unic file .msstyles .The only images are Wallpapers and title of the theme.

**Comment by johngraciliano** [comment]
I am sorry I cannot help much with that.  You can always try to make the images on your own by cropping screenshots.  They would not be very nice because they would lack any transparency, but it is a start.  
Again all the ideas I am presenting are only that: ideas.  I have not actually tried them.  You would need to experiment on your own.

**Comment by maicol07** [comment]
It doesn't work very well...
