### ISSUE TITLE
Scroll bar on the new tab page

### ISSUE THREAD

**Issue by 100fanti** [johngraciliano/simplewhite#37]
Firefox Developer 53 & Nightly 54, (Win 10, screen resolution 1280x1024)
1. Scroll bar on the new tab page with the activated bookmark bar.
![default](https://cloud.githubusercontent.com/assets/25398151/22394388/df9127f0-e530-11e6-8826-53cc04723ef6.png)
2. Incorrect displaying of the video window (The default skin all correctly)
![2017-01-28_074734](https://cloud.githubusercontent.com/assets/25398151/22394396/56192c60-e531-11e6-9520-14369c0372dc.png)
![2](https://cloud.githubusercontent.com/assets/25398151/22394404/79232e4a-e531-11e6-9662-10bd920a8faa.png)

**Comment by johngraciliano** [comment]
There are actually two issues posted here!  Regarding the first (related to the title), I will see what I can do.  On the second one; I only have Windows 8 with a 1366×768 screen and do not experience the problem.  Please include a clean* link where the problem is reflected.  
_________
*Please note I do not use twitter nor facebook (they are very evil)!!!!!

**Comment by 100fanti** [comment]
I have a problem mainly in twitter. (Firefox 53 & 54).
But to somehow show the problem, I publish a clean link on the YouTube video.

https://r4---sn-4g5e6n76.googlevideo.com/videoplayback?key=yt6&ei=OWiOWI_MPM-Yd76lurgK&mm=31&ipbits=0&mn=sn-4g5e6n76&pl=24&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&id=o-AGkWjAVnr5mJoqje-3m5coyxQglQOqGeS1aa37LxgPHS&mt=1485727523&dur=624.988&mv=m&initcwndbps=500000&ms=au&itag=18&requiressl=yes&mime=video%2Fmp4&gir=yes&ip=31.24.95.49&expire=1485749402&ratebypass=yes&lmt=1480756565749420&nh=IgpwcjAyLmZyYTE1KgkxMjcuMC4wLjE&signature=81ADABCA44D4412934B89821389CED833CCD92E1.A4D6950976B565A5B7701C88BF68BA6DEC9D82AC&upn=li8u0q8-OMw&clen=42761491&source=youtube&title=Funny%20CATS%20guaranteed%20to%20make%20you%20laugh%20-%20Funny%20cat%20compilation
![1](https://cloud.githubusercontent.com/assets/25398151/22408597/cdc6c644-e68c-11e6-9182-827580e05654.jpg)
![2](https://cloud.githubusercontent.com/assets/25398151/22408600/d3ea8b82-e68c-11e6-82b3-2932b11bb62f.jpg)

**Comment by johngraciliano** [comment]
Regarding the issue in the title, I normally use smaller thumbnails via a Stylish script I published.  If I do not use that, I do experience the scroll bar in the new tab page, with the default theme and my theme.  That is why I have not cared about that.  I may still do something about it.  I will have to check on your second issue.

**Comment by 100fanti** [comment]
What's new for my issues?

**Comment by johngraciliano** [comment]
[This release](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.01%2BT1) should get rid of the scroll bar in the new tab page.  I believe three rows of tiles should fit in your screen, but if they do not fit properly (including space for the search bar and margins) only two would be presented.  Let me know if there is a problem.  
Regarding the second issue, please open a separate item.  Anyway, I am unclear about the problem, especially because at this moment I do not get anything from the link you provided above.

**Comment by 100fanti** [comment]
The scroll bar has disappeared - this is the main thing.
Two or three rows of tiles does not matter for me, because in the default theme the same happens.
![1](https://cloud.githubusercontent.com/assets/25398151/22729115/622fd6f6-edf2-11e6-826b-28bc2e4c73e4.jpg)
![2](https://cloud.githubusercontent.com/assets/25398151/22729123/6be92d8c-edf2-11e6-8f5a-87c74f28af32.jpg)
![3](https://cloud.githubusercontent.com/assets/25398151/22729126/70493a48-edf2-11e6-923c-331ab84be673.jpg)
![4](https://cloud.githubusercontent.com/assets/25398151/22729131/762fd232-edf2-11e6-83dd-e4deb8cb3c8c.jpg)

**Comment by johngraciliano** [comment]
I am glad you are happy with the solution.  You will find that if you make the window small enough, no tiles will be shown and no scroll bar either.  Yet if you make it too small a scroll bar will be shown because of the space reserved for the search bar.  Note the current solution may have problems in **Firefox 54** if there are more than 10 rows.
